var app = angular.module("portfolio", ['duScroll']);

app.controller("appCtrl", function ($scope, $window) {

    $scope.showPortfolioItem = function (event) {
        let clickedItemID = event.currentTarget.attributes['data-id'].value;
        angular.element(event.currentTarget).addClass('active');

        $scope.modalTitle = $scope.portfolioItems[clickedItemID].name;
        $scope.modalDescription = $scope.portfolioItems[clickedItemID].description;
        $scope.modalImages = $scope.portfolioItems[clickedItemID].imagesList;
        $scope.modalShowcaseImage = $scope.modalImages[0];

        angular.element('#portfolio-modal').modal('show', {
            keyboard: true
        });

        $('#portfolio-modal').on('shown.bs.modal', function () {
            angular.element(".js-modal-image.active").removeClass("active");
            angular.element(".js-modal-image").first().addClass('active');
        }).on('hidden.bs.modal', function (e) {
            angular.element(event.currentTarget).removeClass('active');
        });
    }

    $scope.changeModalShowcaseImage = function (event) {
        $scope.modalShowcaseImage = event.currentTarget.attributes['data-image'].value;
        angular.element(".js-modal-image.active").removeClass("active");
        angular.element(event.target).addClass('active');
    }

    $scope.aboutImageSrc = "https://s-media-cache-ak0.pinimg.com/736x/4d/b7/b7/4db7b7ecb39c4eebc5b8f5358773e4a2.jpg";
    $scope.aboutText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

    $scope.portfolioItems = [
        { name: "MODELOWANIE", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg", "https://lh4.ggpht.com/do-odzhAi9xjCgw1xbyiLc044UMXyvClVBgeyma11W-w0S8b7C7ET-v4-8yk1LgCu40=h310", "https://s-media-cache-ak0.pinimg.com/736x/91/53/d0/9153d09f7e5c1b52a49fc60f0e28b268.jpg", "https://lh3.googleusercontent.com/b1Gp1QGVdNUJ2XbfaEYR9ty2weLWAKISMMhZYgNdigSmlnu2EKQEAstVqNATy9EcTsPb=h310"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "TABULA RASA", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "POŻEGNANIE Z AFRYKĄ", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "BIBLIA GUTENBERGA", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item5", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item6", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item7", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "dupa8", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item9", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item10", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item11", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item12", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item13", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item14", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" },
        { name: "item15", shortDescription: "Lorem ipsum dolor sit amet", portfolioItemImage: "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg", imagesList: ["http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg", "http://images.all-free-download.com/images/graphiclarge/beautiful_nature_landscape_03_hd_picture_166205.jpg", "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg", "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo" }
    ]

    $scope.carouselItems = [
        { name: "TABULA RASA", description: "Lorem ipsum dolor sit amed", src: "http://www.wallpapereast.com/static/images/spring-in-nature-wide-wallpaper-603794.jpg" },
        { name: "POŻEGNANIE Z AFRYKĄ", description: "Lorem ipsum dolor sit amed", src: "http://webneel.com/daily/sites/default/files/images/daily/09-2014/2-nature-photography-pedraterrinha.jpg" },
        { name: "BIBLIA GUTENBERGA", description: "Lorem ipsum dolor sit amed", src: "http://webneel.com/wallpaper/sites/default/files/images/04-2013/natural-scenery-wallpaper.preview.jpg" }
    ]
});



